import { ReportDefinition } from "./report-definition";

const CHANGED = { dimension: "status", operator: "equals" as const, values: ["ADJUSTED", "INVALIDATED"] };

/**
 * Relatórios prontos. Cada um é só uma QuerySpec salva sobre o catálogo — um
 * relatório novo aqui não precisa de rota nem de controller.
 *
 * Só entram relatórios com fonte de dados real. Ficaram de fora do mockup, por
 * falta de dado no banco: faltas/atrasos contra a escala, custo de mão de obra
 * (folha e encargos), aderência a POPs aplicados, marcações fora do perímetro e
 * os recortes por unidade/equipe.
 */
export const SYSTEM_REPORTS: ReportDefinition[] = [
  {
    id: "sys-frequencia",
    system: true,
    code: "FR",
    name: "Frequência e jornada",
    category: "Pessoas",
    description: "Dias trabalhados, horas e média diária por funcionário, a partir das marcações de ponto.",
    visualization: "table",
    spec: {
      dataset: "work_days",
      dimensions: ["employee"],
      measures: ["days_worked", "worked_hours", "avg_daily_hours", "overtime_hours"],
      timeDimension: { dimension: "day" },
      order: [["worked_hours", "desc"]],
    },
    kpis: { measures: ["employee_count", "days_worked", "worked_hours", "avg_daily_hours"] },
    trend: { measure: "worked_hours" },
    usesPeriod: true,
  },
  {
    id: "sys-horas-extras",
    system: true,
    code: "HE",
    name: "Horas acima da jornada",
    category: "Pessoas",
    description: "Quem trabalhou além da jornada diária padrão, em horas e em dias.",
    visualization: "bar",
    spec: {
      dataset: "work_days",
      dimensions: ["employee"],
      measures: ["overtime_hours", "overtime_days", "worked_hours"],
      timeDimension: { dimension: "day" },
      order: [["overtime_hours", "desc"]],
    },
    kpis: { measures: ["overtime_hours", "overtime_days", "employee_count"] },
    trend: { measure: "overtime_hours" },
    usesPeriod: true,
  },
  {
    id: "sys-espelho",
    system: true,
    code: "EP",
    name: "Espelho de ponto",
    category: "Pessoas",
    description: "Um dia por linha: primeira entrada, última saída, períodos e horas de cada funcionário.",
    visualization: "table",
    spec: {
      dataset: "work_days",
      dimensions: ["employee", "day"],
      measures: ["first_in", "last_out", "sessions", "worked_hours", "overtime_hours"],
      timeDimension: { dimension: "day" },
      order: [
        ["employee", "asc"],
        ["day", "asc"],
      ],
    },
    kpis: { measures: ["employee_count", "days_worked", "worked_hours", "overtime_hours"] },
    trend: { measure: "worked_hours" },
    usesPeriod: true,
  },
  {
    id: "sys-auditoria",
    system: true,
    code: "AU",
    name: "Auditoria de marcações",
    category: "Conformidade",
    description: "Marcações ajustadas ou invalidadas, com horário original, autor e justificativa.",
    visualization: "table",
    spec: {
      dataset: "time_entries",
      dimensions: ["employee", "timestamp", "original_timestamp", "status", "adjusted_by", "adjusted_reason"],
      measures: ["entry_count"],
      timeDimension: { dimension: "timestamp" },
      filters: [CHANGED],
      order: [["timestamp", "desc"]],
    },
    kpis: { measures: ["changed_count", "adjusted_count", "invalidated_count", "change_rate"], filters: [] },
    trend: { measure: "entry_count" },
    usesPeriod: true,
  },
  {
    id: "sys-origem",
    system: true,
    code: "OR",
    name: "Origem das marcações",
    category: "Conformidade",
    description: "Marcações por origem (app, manual, reconhecimento facial) e quanto de cada uma foi ajustada.",
    visualization: "bar",
    spec: {
      dataset: "time_entries",
      dimensions: ["source"],
      measures: ["entry_count", "employee_count", "changed_count", "change_rate"],
      timeDimension: { dimension: "timestamp" },
      order: [["entry_count", "desc"]],
    },
    kpis: { measures: ["entry_count", "face_count", "changed_count", "change_rate"] },
    trend: { measure: "entry_count" },
    usesPeriod: true,
  },
  {
    id: "sys-os-tipo",
    system: true,
    code: "OS",
    name: "Ordens de serviço por tipo",
    category: "Operação",
    description: "Volume, conclusão e atraso das ordens de serviço, por tipo de serviço.",
    visualization: "table",
    spec: {
      dataset: "service_orders",
      dimensions: ["type_service"],
      measures: ["order_count", "concluded_count", "completion_rate", "overdue_count"],
      timeDimension: { dimension: "date_init" },
      order: [["order_count", "desc"]],
    },
    kpis: { measures: ["order_count", "concluded_count", "completion_rate", "overdue_count"] },
    trend: { measure: "order_count" },
    usesPeriod: true,
  },
  {
    id: "sys-os-contrato",
    system: true,
    code: "OC",
    name: "Atrasos de OS por contrato",
    category: "Operação",
    description: "Ordens em aberto e com prazo vencido em cada contrato.",
    visualization: "bar",
    spec: {
      dataset: "service_orders",
      dimensions: ["contract"],
      measures: ["overdue_count", "open_count", "overdue_rate", "order_count"],
      timeDimension: { dimension: "date_init" },
      order: [["overdue_count", "desc"]],
    },
    kpis: { measures: ["open_count", "overdue_count", "overdue_rate"] },
    trend: { measure: "overdue_count" },
    usesPeriod: true,
  },
  {
    id: "sys-contratos",
    system: true,
    code: "CT",
    name: "Carteira de contratos",
    category: "Contratos",
    description: "Contratos por órgão, situação, término e valor.",
    visualization: "table",
    spec: {
      dataset: "contracts",
      dimensions: ["contract_number", "org", "status", "date_end"],
      measures: ["total_value"],
      order: [["date_end", "asc"]],
    },
    kpis: { measures: ["contract_count", "active_count", "active_value", "expiring_count"] },
    trend: null,
    usesPeriod: false,
  },
  {
    id: "sys-licitacoes",
    system: true,
    code: "LI",
    name: "Licitações por modalidade",
    category: "Contratos",
    description: "Licitações abertas e finalizadas e o valor estimado, por modalidade.",
    visualization: "bar",
    spec: {
      dataset: "licits",
      dimensions: ["modality"],
      measures: ["licit_count", "open_count", "finished_count", "total_estimated"],
      order: [["licit_count", "desc"]],
    },
    kpis: { measures: ["licit_count", "open_count", "total_estimated"] },
    trend: null,
    usesPeriod: false,
  },
];
